"""Generates microcontroller board descriptions in SKiDL"""

def generate(args, wizard):
    """ Generates microcontroller board descriptions in SKiDL """

    code = '''
#Generated by Swimibowi - SKiDL Microcontroller Board Wizard
"""Creates Kicad netlist file for a microcontroller board"""
from skidl import Bus, Part, Net, generate_netlist

U1 = Part('RF_Module', '{mcu}', footprint='{mcu_footprint}')

NETS = {{}}
NETS['+VBatt'] = Net('+VBatt')
NETS['+VBus'] = Net('+VBus')
NETS['+3V'] = Net('+3V')
NETS['+3V3'] = Net('+3V3')
NETS['+5V'] = Net('+5V')
NETS['GND'] = Net('GND')

U1['VCC'] += NETS['{mcurail}']
U1['GND'] += NETS['GND']
U1['EN'] += NETS['{mcurail}']
U1['GPIO15'] += NETS['GND']
'''.format(**args)

    if args['powersource'] != 'No battery':
        code += '''
BATTERY = Part('Device', 'Battery', footprint='{powersource}')
BATTERY['+'] += NETS['+VBatt']
BATTERY['-'] += NETS['GND']
'''.format(**args)


    if wizard.field('reset'):
        code += '''
NETS['RST'] = Net('RST')
U1['RST'] += NETS['RST']
U1['GPIO16'] += NETS['RST']
'''

    if wizard.field('Reset button'):
        code += '''
SW1 = Part('Switch', 'SW_Push', footprint="Button_Switch_SMD:SW_SPST_B3U-1000P")
SW1[1] += NETS['RST']
SW1[2] += NETS['GND']
'''

    if wizard.field('Flash button'):
        code += '''
SW2 = Part('Switch', 'SW_Push', footprint="Button_Switch_SMD:SW_SPST_B3U-1000P")
SW2[1] += U1['GPIO15']
SW2[2] += NETS['GND']
'''

    if wizard.field('DS18B20'):
        code += '''
NETS['VDD'] = Net('VDD')
NETS['VDD'] += NETS['+VBatt']
NETS['DQ'] = Net('DQ')

U2 = Part('Sensor_Temperature', 'DS18B20', footprint="Package_TO_SOT_THT:TO-92_Inline")
U2['VDD'] += NETS['VDD']
U2['GND'] += NETS['GND']
U2['DQ'] += NETS['DQ']
U1['GPIO2'] += NETS['DQ']
'''
    if wizard.field('DS18B20U'):
        code += '''
NETS['VDD'] = Net('VDD')
NETS['VDD'] += NETS['+VBatt']
NETS['DQ'] = Net('DQ')

U3 = Part('Sensor_Temperature', 'DS18B20U', footprint="Package_SO:MSOP-8_3x3mm_P0.65mm")
U3['VDD'] += NETS['VDD']
U3['GND'] += NETS['GND']
U3['DQ'] += NETS['DQ']
U1['GPIO2'] += NETS['DQ']
'''
    if wizard.field('FTDI header'):
        code += generate_ftdi_header()

    code += '''
generate_netlist()
'''

    return code

def generate_ftdi_header():
    return '''
FTDI_HEADER = Part('Connector', 'Conn_01x06_Female', footprint='Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical')
FTDI_HEADER[1] += NETS['GND']
FTDI_HEADER[2] += NC
FTDI_HEADER[3] += NETS['VDD']
FTDI_HEADER[4] += U1['TX']
FTDI_HEADER[5] += U1['RX']
FTDI_HEADER[6] += NC
'''