#Generated by Swimibowi - SKiDL Microcontroller Board Wizard
"""Creates Kicad netlist file for a microcontroller board"""
from skidl import Bus, Part, Net, generate_netlist

U1 = Part('RF_Module', 'ESP-12E', footprint='RF_Module:ESP-12E')

U1['VCC'] += Net.fetch('+VBatt')
U1['GND'] += Net.fetch('GND')
U1R1 = Part('Device', 'R', value='10k', footprint='Resistor_SMD:R_1206_3216Metric')
U1R2 = Part('Device', 'R', value='4k7', footprint='Resistor_SMD:R_1206_3216Metric')
Net.fetch('+VBatt') & U1R1 & U1['EN']
Net.fetch('GND') & U1R2 & U1['GPIO15']

U1['TX'] += Net.fetch('tx')
U1['RX'] += Net.fetch('rx')

U1['RST'] += Net.fetch('RST')
U1['GPIO16'] += Net.fetch('RST')

SW1 = Part('Switch', 'SW_Push', footprint="Button_Switch_SMD:SW_SPST_B3U-1000P")
SW1[1] += Net.fetch('RST')
SW1[2] += Net.fetch('GND')

SW2 = Part('Switch', 'SW_Push', footprint="Button_Switch_SMD:SW_SPST_B3U-1000P")
SW2[1] += U1['GPIO0']
SW2[2] += Net.fetch('GND')

FTDI_HEADER = Part('Connector', 'Conn_01x06_Female', footprint='Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical')
FTDI_HEADER[1] += Net.fetch('GND')
FTDI_HEADER[2] += NC
FTDI_HEADER[3] += Net.fetch('+VBatt')
FTDI_HEADER[4] += Net.fetch('rx')
FTDI_HEADER[5] += Net.fetch('tx')
FTDI_HEADER[6] += NC

generate_netlist()
