# Generated by Swimibowi - SKiDL Microcontroller Board Wizard
"""Creates Kicad netlist file for a microcontroller board"""

from skidl import subcircuit
from skidl import generate_netlist
from skidl import Net
from skidl import Part


def subcircuit_label(name):
    """Creates subcircuit label footprint"""
    Part('./library/Skimibowi.lib', 'Label', ref=" ", value=name, footprint=f"Skimibowi:label{len(name)}")


def R(value):
    """Creates default resistor footprint"""
    return Part('Device', 'R', value=value, footprint='Resistor_SMD:R_1206_3216Metric')


@subcircuit
def generate_wemos_d1_mini():
    """Generate Wemos D1 footprint"""
    subcircuit_label('wemos_d1_mini')
    global U1
    U1 = Part('MCU_Module', 'WeMOs_D1_mini', footprint='Module:WEMOS_D1_mini_light')
    U1['5V'] += Net.fetch('+VBatt')
    U1['GND'] += Net.fetch('GND')


generate_wemos_d1_mini()


BATTERY = Part('Device', 'Battery', footprint='Battery:BatteryHolder_Keystone_2462_2xAA')
BATTERY['+'] += Net.fetch('+VBatt')
BATTERY['-'] += Net.fetch('GND')

U1['D4'] += Net.fetch('DQ')
Net.fetch('+VBatt') & R('4k7') & Net.fetch('DQ')

U3 = Part('Sensor_Temperature', 'DS18B20U', footprint="Package_SO:MSOP-8_3x3mm_P0.65mm")
U3['VDD'] += Net.fetch('+VBatt')
U3['GND'] += Net.fetch('GND')
U3['DQ'] += Net.fetch('DQ')

Net.fetch('+VBatt') & BATTERY

generate_netlist()
