#Generated by Swimibowi - SKiDL Microcontroller Board Wizard
"""Creates Kicad netlist file for a microcontroller board"""
from skidl import Part, NC, Net, generate_netlist, subcircuit


generate_netlist()
