# Generated by Swimibowi - SKiDL Microcontroller Board Wizard
"""Creates Kicad netlist file for a microcontroller board"""

from skidl import generate_netlist
from skidl import Net
from skidl import Part


generate_netlist()
